### ISSUE TITLE
engine requirement unnecessary for libary

### ISSUE THREAD

**Issue by fxfactorial** [alex996/react-css-spinners#3]
Hi, 

thanks for this lib. I think you should remove the engine requirement, its not needed in this library and preventing installation with yarn. 
```
error react-css-spinners@3.1.1: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.15.0"
error Found incompatible module.
```

**Comment by alex996** [comment]
This is intentional because the lib builds for Node 10 and above. In
theory, it will probably work with Node 8, but I didn't try. I chose Node
10 because it's been LTS since last year, and because Node 8 is going EOL
in Dec. 2019. I suggest you upgrade to v10. (Btw not related to yarn, as
you should be getting the same error with npm).

**Comment by fxfactorial** [comment]
Build time is your issue, not a library user of a pure front end library. The library consumer doesn't have a build step, only you do. Will pass on this lib now.
